Tv7Playlist/Controllers/ChannelApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Tv7Playlist.Data;

namespace Tv7Playlist.Controllers
{
    [Route("api/channels")]
    [ApiController]
    public class ChannelApiController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PlaylistContext _playlistContext;

        public ChannelApiController(ILogger<HomeController> logger, PlaylistContext playlistContext)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _playlistContext = playlistContext ?? throw new ArgumentNullException(nameof(playlistContext));
        }

        [HttpGet]
        [Route("")]
        public async Task<IActionResult> GetAll()
        {
            var playlistEntries =
                await _playlistContext.PlaylistEntries.AsNoTracking().OrderBy(e => e.Position).ToListAsync();
            var result = new {Data = playlistEntries};
            return Ok(result);
        }

        [HttpPut]
        [Route("disable")]
        public async Task<IActionResult> DisableChannels([FromBody] ICollection<Guid> ids)
        {
            if (ids == null) return BadRequest();
            await UpdateEnabledForItems(ids, false);
            return Ok();
        }

        [HttpPut]
        [Route("enable")]
        public async Task<IActionResult> EnableChannels([FromBody] ICollection<Guid> ids)
        {
            if (ids == null) return BadRequest();
            await UpdateEnabledForItems(ids, true);
            return Ok();
        }

        [HttpDelete]
        [Route("")]
        public async Task<IActionResult> DeleteChannels([FromBody] ICollection<Guid> ids)
        {
            if (ids == null) return BadRequest();

            foreach (var id in ids)
            {
                var entry = await _playlistContext.PlaylistEntries.FindAsync(id);
                if (entry == null)
                {
                    _logger.LogDebug($"Could not delete! Channel {id} not found");
                    continue;
                }

                _logger.LogInformation($"Deleting channel {id} - {entry.Name}");
                _playlistContext.PlaylistEntries.Remove(entry);
            }

            await _playlistContext.SaveChangesAsync();

            return Ok();
        }

        private async Task UpdateEnabledForItems(IEnumerable<Guid> ids, bool isEnabled)
        {
            foreach (var id in ids)
            {
                var entry = await _playlistContext.PlaylistEntries.FindAsync(id);
                if (entry == null)
                {
                    _logger.LogDebug($"Could not set enabled state! Channel {id} not found");
                    continue;
                }

                _logger.LogInformation($"Setting enabled of channel {id} - {entry.Name} to {isEnabled}");
                entry.IsEnabled = isEnabled;
                entry.Modified = DateTime.Now;
            }

            await _playlistContext.SaveChangesAsync();
        }
    }
}

Tv7Playlist/Controllers/HomeController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tv7Playlist.Core;
using Tv7Playlist.Data;
using Tv7Playlist.Models;

namespace Tv7Playlist.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAppConfig _appConfig;
        private readonly PlaylistContext _playlistContext;
        private readonly IPlaylistSynchronizer _playlistSynchronizer;

        public HomeController(PlaylistContext playlistContext, IPlaylistSynchronizer playlistSynchronizer, IAppConfig appConfig)
        {
            _playlistContext = playlistContext ?? throw new ArgumentNullException(nameof(playlistContext));
            _playlistSynchronizer = playlistSynchronizer ?? throw new ArgumentNullException(nameof(playlistSynchronizer));
            _appConfig = appConfig ?? throw new ArgumentNullException(nameof(appConfig));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var playlistEntries = await _playlistContext.PlaylistEntries.AsNoTracking().OrderBy(e => e.Position)
                .Select(e => new PlaylistEntryModel(e)).ToListAsync();
            var model = new HomeModel(playlistEntries);

            return View(model);
        }

        [HttpGet]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var errorViewModel = new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier};

            return View(errorViewModel);
        }

        [HttpGet]
        [Route("synchronize")]
        public IActionResult Synchronize()
        {
            var homeSynchronizeModel = new HomeSynchronizeModel(_appConfig.TV7Url);
            return View(homeSynchronizeModel);
        }

        [HttpPost]
        [Route("synchronize")]
        public async Task<IActionResult> Synchronize(bool ok)
        {
            await _playlistSynchronizer.SynchronizeAsync();

            return RedirectToAction("Index", "Home");
        }

       
    }
}

Tv7Playlist/Controllers/PlaylistEntryController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tv7Playlist.Data;

namespace Tv7Playlist.Controllers
{
    public class PlaylistEntryController : Controller
    {
        private readonly PlaylistContext _playlistContext;

        public PlaylistEntryController(PlaylistContext playlistContext)
        {
            _playlistContext = playlistContext ?? throw new ArgumentNullException(nameof(playlistContext));
        }

        [HttpGet]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return NotFound();

            var entry = await _playlistContext.PlaylistEntries.FindAsync(id);
            if (entry == null) return NotFound();

            return View(entry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, PlaylistEntry updatedEntry)
        {
            if (updatedEntry == null) return NotFound();

            if (id != updatedEntry.Id) return NotFound();

            if (ModelState.IsValid)
            {
                var entry = await _playlistContext.PlaylistEntries.FindAsync(id);
                if (entry == null) return NotFound();

                entry.Position = updatedEntry.Position;
                entry.ChannelNumberExport = updatedEntry.ChannelNumberExport;
                entry.EpgMatchName = updatedEntry.EpgMatchName;
                entry.IsEnabled = updatedEntry.IsEnabled;
                entry.LogoUrl = updatedEntry.LogoUrl;
                entry.Modified = DateTime.Now;

                await _playlistContext.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }

            return View(updatedEntry);
        }
    }
}

Tv7Playlist/Views/Home/Index.cshtml
@model HomeModel;
@{
    ViewData["Title"] = "TV7 Playlist";
}

<form method="post">
    <div class="row">
        <div class="col col-12">
            <table class="table table-hover table-striped" id="playlistTable">
                <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th>Number Import</th>
                    <th>Number Export</th>
                    <th>Position</th>
                    <th>Name</th>
                    <th>EPG Name</th>
                    <th>Enabled</th>
                    <th>Available</th>
                    <th>URL Proxy</th>
                    <th>URL Original</th>
                    <th>Created</th>
                    <th>Modified</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
                <tfoot>
                    <th></th>
                    <th></th>
                    <th>Number Import</th>
                    <th>Number Export</th>
                    <th>Position</th>
                    <th>Name</th>
                    <th>EPG Name</th>
                    <th>Enabled</th>
                    <th>Available</th>
                    <th>URL Proxy</th>
                    <th>URL Original</th>
                    <th>Created</th>
                    <th>Modified</th>
                </tfoot>
            </table>
        </div>
    </div>
    <script>
const urlGet = '@Url.Action("GetAll", "ChannelApi")';
const urlEnable = '@Url.Action("EnableChannels", "ChannelApi")';
const urlDisable = '@Url.Action("DisableChannels", "ChannelApi")';
const urlDelete = '@Url.Action("DeleteChannels", "ChannelApi")';
const urlEdit = '@Url.Action("Edit", "PlaylistEntry")';

$(document).ready(function() {
    $('#playlistTable').DataTable({
        "ajax": urlGet,
        dom: 'Bfrtip',
        pageLength: 25,
        columns: [  
            {  
                data: null,
                render: function ( data, type, row ) {return null;}  
            },  
            {  
                data: "id",  
                name: "eq",  
                visible: false,  
                searchable: false  
            },  
            {  
                data: "channelNumberImport",  
            },
            {  
                data: "channelNumberExport",  
            },
            {  
                data: "position",  
            },
            {  
                data: "name",  
            },
            {  
                data: "epgMatchName",  
            },
            {  
                data: "isEnabled",
                searchable: false,  
                render: function ( data, type, row, meta ) {
                    if (data) {
                        return '<span class="text-primary">Enabled</span>'
                    } else {
                        return '<span class="text-danger">Disabled</span>'
                    }
                }  
            },
            {  
                data: "isAvailable",  
                searchable: false,  
                render: function ( data, type, row, meta ) {
                    if (data) {
                        return '<span class="text-primary">yes</span>'
                    } else {
                        return '<span class="text-danger">no</span>'
                    }
                }  
            },
            {  
                data: "urlProxy",  
            },
            {  
                data: "urlOriginal",  
            },
            {  
                data: "created",  
                searchable: false,  
                render: function ( data, type, row, meta ) {
                    return moment(data).format('YYYY-MM-DD HH:mm');
                }  
            },
            {  
                data: "modified",  
                searchable: false,  
                render: function ( data, type, row, meta ) {
                    return moment(data).format('YYYY-MM-DD HH:mm');
                }  
            }
        ],  
        columnDefs: [
            {
                orderable: false,
                searchable: false,
                className: 'select-checkbox',
                targets:   [0]
            },
            {
                visible: false,
                targets:   [1]
            },
            {
                orderable: false,
                targets:   [0,1,9,10]
            },
            {
                searchable: false,
                targets:   [0,9,10,11,12]
            },
        ],
        select: {
            style:    'multi',
            selector: 'td:first-child'
        },
        buttons: [
            'pageLength',
            'selectAll',
            'selectNone',
            {
                extend: 'selected',
                text: 'Disable selected',
                enabled: false,
                className: 'btn btn-warning',
                action: function ( e, dt, node, config ) {
                    const ids = $.map(dt.rows({ selected: true }).data(), function (item) {
                        return item.id;
                    });
                    setEnabledForChannels(urlDisable, ids, dt);
                },
            },
            {
                extend: 'selected',
                text: 'Enable selected',
                enabled: false,
                className: 'btn btn-info',
                action: function ( e, dt, node, config ) {
                    const ids = $.map(dt.rows({ selected: true }).data(), function (item) {
                        return item.id;
                    });
                    setEnabledForChannels(urlEnable, ids, dt);
                },
            },
            {
                extend: 'selected',
                text: 'Delete selected',
                enabled: false,
                className: 'btn btn-danger',
                action: function ( e, dt, node, config ) {
                    const ids = $.map(dt.rows({ selected: true }).data(), function (item) {
                        return item.id;
                    });
                    if (confirm("Do you really want to delete the " + ids.length + " selected channel(s)?")) {
                        deleteChannels(ids, dt);
                    }
                },
            },
            {
                extend: 'selectedSingle',
                text: 'Edit entry',
                enabled: false,
                className: 'btn btn-secondary',
                action: function ( e, dt, node, config ) {
                    const id = dt.rows({ selected: true}).data()[0].id;
                    window.location.href = urlEdit + '/' +id;
                },
            }
        ]
    });
});

function setEnabledForChannels(url, ids, dataTable) {  
    const options = {};  
    options.url = url;  
    options.type = "PUT";
    options.data = JSON.stringify(ids);  
    options.contentType = "application/json";  
    options.dataType = "html";  
    options.success = function (msg) {  
        dataTable.ajax.reload();  
    };  
    options.error = function () {  
        alert("Error while calling the Web API!");  
    };  
    $.ajax(options);  
}

function deleteChannels(ids, dataTable) {  
    const options = {};  
    options.url = urlDelete;  
    options.type = "DELETE";
    options.data = JSON.stringify(ids);  
    options.contentType = "application/json";  
    options.dataType = "html";  
    options.success = function (msg) {  
        dataTable.ajax.reload();  
    };  
    options.error = function () {  
        alert("Error while calling the Web API!");  
    };  
    $.ajax(options);  
}
</script>
</form>

Tv7Playlist/Views/Home/Synchronize.cshtml
@model HomeSynchronizeModel;
@{
    ViewData["Title"] = "TV7 Playlist - Synchronize";
}

<div class="row">
    <div class="col offset-3 col-7">
        <h3>Synchronize TV7 playlist</h3>
    </div>
</div>

<div class="row">
    <div class="col offset-3 col-1">
        Synchronization URL: 
    </div>
    <div class="col col-2">
        @Model.SynchronizationUrl 
    </div>
</div>

<div class="row">
    <div class="col offset-3 col-7">
        <form asp-action="Synchronize">
            <input type="hidden" id="ok" value="true"/>
            <input type="submit" value="Run Synchronization" class="btn btn-primary"/>
        </form>
    </div>
</div>